version: "3"

networks:
  default:
    external:
      name: revelio-labs-assignment
services:
  dashboard:
    image: revelio-labs-assignment-dashboard:latest
    build: .
    env_file: .env
    command: [sh, -c, "app/scripts/wait_for_db.sh && app/scripts/entrypoint.sh && app/scripts/run_app.sh"]
    depends_on:
      - postgres
    ports:
      - 3838:3838

  postgres:
    image: postgres:11.2
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./scripts/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql